//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.11 at 07:19:01 PM ICT 
//


package id.co.quadras.qif.engine.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="driver" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="username" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="password" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="validationQuery" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="initialSize" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="maxActive" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="maxIdle" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="minIdle" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="testOnBorrow" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="jmxEnabled" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="testWhileIdle" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="testOnReturn" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="minEvictableIdleTimeMillis" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="validationInterval" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="timeBetweenEvictionRunsMillis" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="maxWait" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="logAbandoned" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="removeAbandoned" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="removeAbandonedTimeout" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="jdbcInterceptors" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "dataSource")
public class DataSource {

    @XmlValue
    protected String value;
    @XmlAttribute
    protected String type;
    @XmlAttribute
    protected String url;
    @XmlAttribute
    protected String driver;
    @XmlAttribute
    protected String username;
    @XmlAttribute
    protected String password;
    @XmlAttribute
    protected String validationQuery;
    @XmlAttribute
    protected String initialSize;
    @XmlAttribute
    protected String maxActive;
    @XmlAttribute
    protected String maxIdle;
    @XmlAttribute
    protected String minIdle;
    @XmlAttribute
    protected String testOnBorrow;
    @XmlAttribute
    protected String jmxEnabled;
    @XmlAttribute
    protected String testWhileIdle;
    @XmlAttribute
    protected String testOnReturn;
    @XmlAttribute
    protected String minEvictableIdleTimeMillis;
    @XmlAttribute
    protected String validationInterval;
    @XmlAttribute
    protected String timeBetweenEvictionRunsMillis;
    @XmlAttribute
    protected String maxWait;
    @XmlAttribute
    protected String logAbandoned;
    @XmlAttribute
    protected String removeAbandoned;
    @XmlAttribute
    protected String removeAbandonedTimeout;
    @XmlAttribute
    protected String jdbcInterceptors;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the driver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriver() {
        return driver;
    }

    /**
     * Sets the value of the driver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriver(String value) {
        this.driver = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the validationQuery property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidationQuery() {
        return validationQuery;
    }

    /**
     * Sets the value of the validationQuery property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidationQuery(String value) {
        this.validationQuery = value;
    }

    /**
     * Gets the value of the initialSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitialSize() {
        return initialSize;
    }

    /**
     * Sets the value of the initialSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitialSize(String value) {
        this.initialSize = value;
    }

    /**
     * Gets the value of the maxActive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxActive() {
        return maxActive;
    }

    /**
     * Sets the value of the maxActive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxActive(String value) {
        this.maxActive = value;
    }

    /**
     * Gets the value of the maxIdle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxIdle() {
        return maxIdle;
    }

    /**
     * Sets the value of the maxIdle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxIdle(String value) {
        this.maxIdle = value;
    }

    /**
     * Gets the value of the minIdle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinIdle() {
        return minIdle;
    }

    /**
     * Sets the value of the minIdle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinIdle(String value) {
        this.minIdle = value;
    }

    /**
     * Gets the value of the testOnBorrow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestOnBorrow() {
        return testOnBorrow;
    }

    /**
     * Sets the value of the testOnBorrow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestOnBorrow(String value) {
        this.testOnBorrow = value;
    }

    /**
     * Gets the value of the jmxEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJmxEnabled() {
        return jmxEnabled;
    }

    /**
     * Sets the value of the jmxEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJmxEnabled(String value) {
        this.jmxEnabled = value;
    }

    /**
     * Gets the value of the testWhileIdle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestWhileIdle() {
        return testWhileIdle;
    }

    /**
     * Sets the value of the testWhileIdle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestWhileIdle(String value) {
        this.testWhileIdle = value;
    }

    /**
     * Gets the value of the testOnReturn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestOnReturn() {
        return testOnReturn;
    }

    /**
     * Sets the value of the testOnReturn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestOnReturn(String value) {
        this.testOnReturn = value;
    }

    /**
     * Gets the value of the minEvictableIdleTimeMillis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinEvictableIdleTimeMillis() {
        return minEvictableIdleTimeMillis;
    }

    /**
     * Sets the value of the minEvictableIdleTimeMillis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinEvictableIdleTimeMillis(String value) {
        this.minEvictableIdleTimeMillis = value;
    }

    /**
     * Gets the value of the validationInterval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidationInterval() {
        return validationInterval;
    }

    /**
     * Sets the value of the validationInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidationInterval(String value) {
        this.validationInterval = value;
    }

    /**
     * Gets the value of the timeBetweenEvictionRunsMillis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeBetweenEvictionRunsMillis() {
        return timeBetweenEvictionRunsMillis;
    }

    /**
     * Sets the value of the timeBetweenEvictionRunsMillis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeBetweenEvictionRunsMillis(String value) {
        this.timeBetweenEvictionRunsMillis = value;
    }

    /**
     * Gets the value of the maxWait property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxWait() {
        return maxWait;
    }

    /**
     * Sets the value of the maxWait property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxWait(String value) {
        this.maxWait = value;
    }

    /**
     * Gets the value of the logAbandoned property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogAbandoned() {
        return logAbandoned;
    }

    /**
     * Sets the value of the logAbandoned property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogAbandoned(String value) {
        this.logAbandoned = value;
    }

    /**
     * Gets the value of the removeAbandoned property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemoveAbandoned() {
        return removeAbandoned;
    }

    /**
     * Sets the value of the removeAbandoned property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemoveAbandoned(String value) {
        this.removeAbandoned = value;
    }

    /**
     * Gets the value of the removeAbandonedTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemoveAbandonedTimeout() {
        return removeAbandonedTimeout;
    }

    /**
     * Sets the value of the removeAbandonedTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemoveAbandonedTimeout(String value) {
        this.removeAbandonedTimeout = value;
    }

    /**
     * Gets the value of the jdbcInterceptors property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJdbcInterceptors() {
        return jdbcInterceptors;
    }

    /**
     * Sets the value of the jdbcInterceptors property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJdbcInterceptors(String value) {
        this.jdbcInterceptors = value;
    }

}
