//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.08 at 10:28:41 PM WIT 
//


package id.co.quadras.qif.engine.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}dbSettings"/>
 *         &lt;element ref="{}transactionManager"/>
 *         &lt;element ref="{}dataSource"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dbSettings",
    "transactionManager",
    "dataSource"
})
@XmlRootElement(name = "databaseRepository")
public class DatabaseRepository {

    @XmlElement(required = true)
    protected DbSettings dbSettings;
    @XmlElement(required = true)
    protected TransactionManager transactionManager;
    @XmlElement(required = true)
    protected DataSource dataSource;

    /**
     * set value to "" for defaultStatementTimeout if the JDBC driver doesn't support it, for example : PostgreSQL
     * 
     * @return
     *     possible object is
     *     {@link DbSettings }
     *     
     */
    public DbSettings getDbSettings() {
        return dbSettings;
    }

    /**
     * Sets the value of the dbSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbSettings }
     *     
     */
    public void setDbSettings(DbSettings value) {
        this.dbSettings = value;
    }

    /**
     * transactionManager = JDBC or MANAGED 
     *         JDBC This configuration simply makes use of the JDBC commit and rollback facilities directly.
     *         It relies on the connection retrieved from the dataSource to manage the scope of the transaction
     * 
     * @return
     *     possible object is
     *     {@link TransactionManager }
     *     
     */
    public TransactionManager getTransactionManager() {
        return transactionManager;
    }

    /**
     * Sets the value of the transactionManager property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionManager }
     *     
     */
    public void setTransactionManager(TransactionManager value) {
        this.transactionManager = value;
    }

    /**
     * MANAGED This configuration simply does almost nothing.
     *          It never commits, or rolls back a connection.
     *          Instead, it lets the container manage the full lifecycle of the transaction (e.g. a JEE Application Server context).
     *          By default it does close the connection.
     *          However, some containers don't expect this, and thus if you need to stop it from closing the connection,
     *          set the "closeConnection" property to false
     *         
     *         <transactionManager type="MANAGED" closeConnection="false"
     * 
     *          dataSource = POOLED or JNDI 
     *         POOLED This implementation of DataSource pools JDBC Connection objects
     *         to avoid the initial connection and authentication time required to create a new Connection instance.
     * 
     * @return
     *     possible object is
     *     {@link DataSource }
     *     
     */
    public DataSource getDataSource() {
        return dataSource;
    }

    /**
     * Sets the value of the dataSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSource }
     *     
     */
    public void setDataSource(DataSource value) {
        this.dataSource = value;
    }

}
