//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.11 at 07:19:01 PM ICT 
//


package id.co.quadras.qif.engine.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the id.co.quadras.qif.engine.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: id.co.quadras.qif.engine.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TransactionManager }
     * 
     */
    public TransactionManager createTransactionManager() {
        return new TransactionManager();
    }

    /**
     * Create an instance of {@link BatchConfig }
     * 
     */
    public BatchConfig createBatchConfig() {
        return new BatchConfig();
    }

    /**
     * Create an instance of {@link DataSource }
     * 
     */
    public DataSource createDataSource() {
        return new DataSource();
    }

    /**
     * Create an instance of {@link Qif }
     * 
     */
    public Qif createQif() {
        return new Qif();
    }

    /**
     * Create an instance of {@link RootPackage }
     * 
     */
    public RootPackage createRootPackage() {
        return new RootPackage();
    }

    /**
     * Create an instance of {@link DatabaseRepository }
     * 
     */
    public DatabaseRepository createDatabaseRepository() {
        return new DatabaseRepository();
    }

    /**
     * Create an instance of {@link DbSettings }
     * 
     */
    public DbSettings createDbSettings() {
        return new DbSettings();
    }

}
